name: DuckDB Workflow Trigger
on:
  workflow_dispatch:
    inputs:
      # Git ref of the duckdb repo
      duckdb-ref:
        required: true
        type: string
      trigger-nightly:
        required: true
        type: boolean
  schedule:
    - cron: "17 0 * * *"

jobs:
  build-linux:
    runs-on: ubuntu-latest

    env:
      PAT_USER: ${{ secrets.PAT_USER }}
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

    steps:
    - uses: actions/checkout@v3

    - name: Trigger DuckDB workflows (main branch)
      if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.trigger-nightly }}
      run: |
        ./trigger.sh duckdb '{"event_type": "nightly-build"}'
        #./trigger.sh duckdb-node '{"event_type": "nightly-build"}'

    - name: Trigger DuckDB workflows (feature)
      if: ${{ github.event_name != 'workflow_dispatch' }}
      run: |
        ./trigger.sh duckdb '{"ref":"refs/heads/feature"}' NightlyTests.yml
        ./trigger.sh duckdb '{"ref":"refs/heads/feature"}' OSX.yml

    - name: Trigger DuckDB-Wasm workflow (in duckdb)
      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.trigger-nightly == 0 }}
      run: |
        ./trigger.sh duckdb '{"ref":"refs/heads/main","inputs":{"release_s3":"true", "duckdb-ref":"${{ github.event.inputs.duckdb-ref }}"}}' Wasm.yml
